### ISSUE TITLE
Unsupported state or unable to authenticate data

### ISSUE THREAD

**Issue by TheCuteFoxxy** [MauriceButler/cryptr#40]
```
node:internal/crypto/cipher:193
  const ret = this[kHandle].final();
                            ^
Error: Unsupported state or unable to authenticate data
    at Decipheriv.final (node:internal/crypto/cipher:193:29)
    at Cryptr.decrypt (/home/container/node_modules/cryptr/index.js:55:54)
    at Client.<anonymous> (/home/container/client.js:95:27)
```
**Key (Modified from live key, but same charset)**: 
```
MIIEowIBAAKCAQEAiVxtJ2dOj08jMg75NLlEBk9KL/UBEbAHxBUvKgXZxTiEf0E1KIv2JrC6mj8zodmTqWzy2m1wii7wZPBwde1mOWu8Rym6WuD/iiXXgnW/7bbCgunLsdXF5jSAjLvP6Ua4P3M/UWEO5lY1DxkfE1n+Rd3KdSiouCjCHJM+uAi5A0kDEi0689uDaQW88mdlHh3sIbafM+NEWzw3HIeJYJzg+YoX8v1pa8ouHfbsRqI11PtAvXrIKv2mH52zflWn9dbVeW6ZS7925TxN0cDqJYlUzua5RZ6iDxi3T3LQACVDO9w1uWSXAyyqm05Gr+0Q3Cbr/FiKtBs6+f7Z+ohjSC98HQIDAQABAoIBAFD0B+CRIduT6Eo4SX2JMm7FjNN2sYqbE/icA4/gotd4152n8IxU8F0dCtydIvDgKgZQD1Br70eBImxax+y4XOa6d9v427tznybr5nccrmCKtVgyMbo9IsTpbFmE1qPE6hF6+nYbnYxigiLDy2y8PP8wF4G01Lq0SrJMlUog2ej01zuIz+qgvovsP2hS3nZEcIR/rvqa7MuDLt//V0qwTrnmgDfUGLUFzhzdoEFwWec0w8E2mlovVGQ0rienVSHRL05tzzOEwTEJadh+OcCH1DrFeLV23cOAEAitdzDJUeJ+4/3tNvLgOFptn1DgFmEF/jBkahwSs/Kb2nTRs7VMoIECgYEA/sWgdIDXB4RCTLi4t7I7iCbWqh2RyLt2SpbAtK0LN11pJnc17+n9iBLwj7yrKS4vqMw+5U9Cl3lD1tW6f8yAWvhelaWMAcsddxvL8hzYH+4oRxZO51lI0lGEeht3C7CJ0Jqo56d8xPDYncnh0IKcj/aj79S3reKcOOLjm6HaIdcCgYEAigXr7jHLKD5olg3ekPCjJBRuW1r4xxZw6RuiaHdIiHSJwgAsvznon9/kO6uUCAqYZ9zo/GkidqjWB1Bxm3sqP8GPE1Xlexu/N6BFBTExLM0PjLr6w3GIE5hagWJzPI5kYVLLdC7IAGzpgXVsxHpwfSxKK06MYSb5xGbjFGHS+ysCgYEAjRBhwoAgD3Jkv1Q8OsH+Amn2y+RpduqNGcmU07VIk5QuB3VUMQ2vKmvKNNvzLW78RosofBFBvtsO++IFTIOvwi7pOBSci9Wp7+w9JUZhSHS2an3onGIsVv95yZ5xcNCDzjQEN5feFrGATwWb+baH95JJvR5bwXTKqRi/i8m3HKsCgYAyAxFJPwuxKmP1M1NZS4ihszGFssIASbZiERxZJBfJMgkUncGZDN+oxpTJtlMuUsCEqfxWMbZGLslW3yQ7RXa6oWU5iV9cq2IvQsifqAJ8jFU9Fid1GDdJemQZC9Zbs/DVfw2vrJ/V36EAws7FpuQJxzmc1ZpyPZA1RV607Plo/wKBgCwRixBZ3+ImuiOeCzkE6nzCwiPzVEMV3YPRFP6HgQcqutdIS47i0NqlryriZW15x4OtcRJ3nT8ce2HLL1iuTbiJJ48e8K57V2x7iT76O7ZjYFQF9qymHbnmGWtUKmJD0Kf6aOs5nI+bFtJ53ob7aU0BE8tinc+ant46fyyEwEGI
```

**Data Being Encrypted:**
`financial@azrael.gg`

When encrypting the data, there are no errors and the encryption occurs as expected. However, when attempting to decrypt the data, the error occurs. I have also tried changing the key and re-encrypting and decrypting the data but the error persists.

**Comment by TheCuteFoxxy** [comment]
Closing this out, if you are running multiple files at once in a Node environment and redeclare `cryptr` in the different files, it will cause this.

I changed from declaring it once in each file, to declaring it as a global (`global.cryptr`) in the file that runs first and the issue was resolved.

**Comment by TheCuteFoxxy** [comment]
Reopening because this issue is persisting.

Node Version: 16
Cryptr Version: 6.0.3

This only occurs when across processes (and has only started since moving to Node 16). Node 14 does not encounter this issue and I can use the identical key across processes without issues.

**Comment by TheElegantCoding** [comment]
As I see it, you have a Node project, I have a Next.js project, and I get the same error. This is when you encrypt data and decrypt data with a different secret

**Comment by TheElegantCoding** [comment]
The problem is, this error is runtime and crashes the server. i don't know how to handle this error properly
